# Generated by Django 3.2.12 on 2022-03-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='conservation_strategies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habitat',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habitat',
            name='invasive_species',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habitat',
            name='threats',
            field=models.TextField(null=True),
        ),
    ]
